name: custom_camera
version: 4.3.4
description: |
  A camera picker for Flutter projects based on WeChat's UI,
  which is also a separate runnable extension to the
  wechat_assets_picker.
topics:
  - picker
  - camera
  - image
  - video
  - wechat

repository: https://github.com/fluttercandies/flutter_wechat_camera_picker
issue_tracker: https://github.com/fluttercandies/flutter_wechat_camera_picker/issues

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  wechat_picker_library: ^1.0.5

  camera: ^0.10.5+9
  camera_android: ^0.10.9+16
  camera_platform_interface: ^2.8.0

  collection: '>=1.18.0 <2.0.0'
#  path: ^1.8.0
  photo_manager: ^3.2.3
  photo_manager_image_provider: ^2.0.0
  sensors_plus: '>=4.0.0 <6.0.0'
  video_player: ^2.7.0

dev_dependencies:
  flutter_lints: any

